/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;
import javax.swing.table.DefaultTableModel;

/**
 * @author Victor Nivelo
 */
public class Compra extends javax.swing.JDialog {

    /**
     * Creates new form Compra
     */
    DefaultTableModel modelo;
    public Compra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        /*modelo = new DefaultTableModel();
        modelo.addColumn("Producto");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio unitario");
        modelo.addColumn("Total");
        this.tblProductos.setModel(modelo);*/
      
        /*DatosCliente datosCliente = new DatosCliente();
        txtNombre.setText(datosCliente.Nombre);    */    
    }
    public static String Nombre = " ";
    public static String Apellido = " ";
    public static String Telefono = " ";    
    public static String TarjetaCredito = " ";
    public static String TarjetaDebito = " ";
    public static String Efectivo = " ";
    public static String DebitoBancario = " ";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        try {
            btngMetodoPago =(javax.swing.ButtonGroup)java.beans.Beans.instantiate(getClass().getClassLoader(), "gui.Compra_buttonGroup3");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        panNombreEmpresa = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        panDatosCliente = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        lblNumeroCelular = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtNumeroCelular = new javax.swing.JTextField();
        panProductosCompra = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        panFactura = new javax.swing.JPanel();
        lblTotalSinIVA = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblValorIVA = new javax.swing.JLabel();
        lblPrecioConIVA = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txtValorDelIVA = new javax.swing.JTextField();
        txtPrecioConIVA = new javax.swing.JTextField();
        txtSubtotal = new javax.swing.JTextField();
        txtTotalSinIVA = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        panMetodoPago = new javax.swing.JPanel();
        rbtnTarjetaCredito = new javax.swing.JRadioButton();
        rbtnTarjetaDebito = new javax.swing.JRadioButton();
        rbtnEfecivo = new javax.swing.JRadioButton();
        rbtnDebidoBancario = new javax.swing.JRadioButton();
        panNombreEnpresa = new javax.swing.JPanel();
        lblDireccion = new javax.swing.JLabel();
        lblAutorizacion = new javax.swing.JLabel();
        btnAgregarProducto = new javax.swing.JButton();
        btnImprimirFactura = new javax.swing.JButton();
        btnAgregarCliente = new javax.swing.JButton();
        btnCancelarPedido = new javax.swing.JButton();
        lblImagenLogo = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("INGRESO DE DATOS");

        panNombreEmpresa.setBackground(new java.awt.Color(204, 204, 204));
        panNombreEmpresa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 28, 112), 2, true));

        lblLogo.setBackground(new java.awt.Color(153, 255, 204));
        lblLogo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(0, 153, 255));
        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setText("HELADERIA PINGUINO");

        panDatosCliente.setBackground(new java.awt.Color(204, 204, 204));
        panDatosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 51), 1, true), "DATOS CLIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 0, 153))); // NOI18N

        lblNombre.setForeground(new java.awt.Color(255, 0, 0));
        lblNombre.setText("Nombre:");

        lblApellido.setForeground(new java.awt.Color(255, 0, 0));
        lblApellido.setText("Apellidos:");

        lblCedula.setForeground(new java.awt.Color(204, 0, 0));
        lblCedula.setText("Cedula:");

        lblNumeroCelular.setForeground(new java.awt.Color(204, 0, 0));
        lblNumeroCelular.setText("Celular:");

        javax.swing.GroupLayout panDatosClienteLayout = new javax.swing.GroupLayout(panDatosCliente);
        panDatosCliente.setLayout(panDatosClienteLayout);
        panDatosClienteLayout.setHorizontalGroup(
            panDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDatosClienteLayout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombre))
                    .addGroup(panDatosClienteLayout.createSequentialGroup()
                        .addGroup(panDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblApellido)
                            .addComponent(lblCedula)
                            .addComponent(lblNumeroCelular))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellido)
                            .addComponent(txtCedula)
                            .addComponent(txtNumeroCelular, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        panDatosClienteLayout.setVerticalGroup(
            panDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedula)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroCelular)
                    .addComponent(txtNumeroCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panProductosCompra.setBackground(new java.awt.Color(204, 204, 204));
        panProductosCompra.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 51), 1, true), "PRODUCTOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 0, 153))); // NOI18N

        tblProductos.setBackground(new java.awt.Color(236, 235, 235));
        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Helado de Menta", "3", "0.25", "0.75"},
                {"Cono de Vainilla", "1", "1.50", "1.50"},
                {"Galleta de limon", "2", "0.50", "1.00"},
                {"Pastel helado de gelatino", "1", "2.50", "2.50"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Precio Unitario", ""
            }
        ));
        tblProductos.setSelectionBackground(new java.awt.Color(255, 255, 204));
        jScrollPane7.setViewportView(tblProductos);

        javax.swing.GroupLayout panProductosCompraLayout = new javax.swing.GroupLayout(panProductosCompra);
        panProductosCompra.setLayout(panProductosCompraLayout);
        panProductosCompraLayout.setHorizontalGroup(
            panProductosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panProductosCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panProductosCompraLayout.setVerticalGroup(
            panProductosCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panProductosCompraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );

        panFactura.setBackground(new java.awt.Color(204, 204, 204));
        panFactura.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 51), 1, true), "Facturacion", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(153, 0, 153))); // NOI18N

        lblTotalSinIVA.setText("Total sin IVA:");

        lblSubtotal.setText("Subtotal:");

        lblValorIVA.setText("Valor deL IVA");

        lblPrecioConIVA.setText("Precio con IVA");

        lblTotal.setText("TOTAL");

        txtValorDelIVA.setText("$ 0.69");

        txtPrecioConIVA.setText("$ 6.94");

        txtSubtotal.setText("$ 5.75");

        txtTotalSinIVA.setText("$ 5.75");

        txtTotal.setText("$ 6.94");

        javax.swing.GroupLayout panFacturaLayout = new javax.swing.GroupLayout(panFactura);
        panFactura.setLayout(panFacturaLayout);
        panFacturaLayout.setHorizontalGroup(
            panFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panFacturaLayout.createSequentialGroup()
                        .addGroup(panFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrecioConIVA)
                            .addComponent(lblTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecioConIVA, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(txtTotal)))
                    .addGroup(panFacturaLayout.createSequentialGroup()
                        .addComponent(lblTotalSinIVA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotalSinIVA))
                    .addGroup(panFacturaLayout.createSequentialGroup()
                        .addComponent(lblSubtotal)
                        .addGap(35, 35, 35)
                        .addComponent(txtSubtotal))
                    .addGroup(panFacturaLayout.createSequentialGroup()
                        .addComponent(lblValorIVA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValorDelIVA))))
        );
        panFacturaLayout.setVerticalGroup(
            panFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFacturaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalSinIVA)
                    .addComponent(txtTotalSinIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubtotal)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorIVA)
                    .addComponent(txtValorDelIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioConIVA)
                    .addComponent(txtPrecioConIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panMetodoPago.setBackground(new java.awt.Color(204, 204, 204));
        panMetodoPago.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 1, true), "Metodo de pago", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(153, 0, 153))); // NOI18N

        btngMetodoPago.add(rbtnTarjetaCredito);
        rbtnTarjetaCredito.setText("Tarjeta de credito");

        btngMetodoPago.add(rbtnTarjetaDebito);
        rbtnTarjetaDebito.setText("Tarjeta de debito");

        btngMetodoPago.add(rbtnEfecivo);
        rbtnEfecivo.setText("Efectivo");

        btngMetodoPago.add(rbtnDebidoBancario);
        rbtnDebidoBancario.setText("Debito bancario");

        javax.swing.GroupLayout panMetodoPagoLayout = new javax.swing.GroupLayout(panMetodoPago);
        panMetodoPago.setLayout(panMetodoPagoLayout);
        panMetodoPagoLayout.setHorizontalGroup(
            panMetodoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMetodoPagoLayout.createSequentialGroup()
                .addGroup(panMetodoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnTarjetaCredito)
                    .addComponent(rbtnTarjetaDebito)
                    .addComponent(rbtnEfecivo)
                    .addComponent(rbtnDebidoBancario))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panMetodoPagoLayout.setVerticalGroup(
            panMetodoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMetodoPagoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbtnTarjetaCredito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnTarjetaDebito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnEfecivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnDebidoBancario))
        );

        panNombreEnpresa.setBackground(new java.awt.Color(204, 204, 204));

        lblDireccion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDireccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDireccion.setText("Direccion: 10 de agosto y 24 de mayo");

        lblAutorizacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAutorizacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAutorizacion.setText("Autorizacion:");

        javax.swing.GroupLayout panNombreEnpresaLayout = new javax.swing.GroupLayout(panNombreEnpresa);
        panNombreEnpresa.setLayout(panNombreEnpresaLayout);
        panNombreEnpresaLayout.setHorizontalGroup(
            panNombreEnpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panNombreEnpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panNombreEnpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAutorizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panNombreEnpresaLayout.setVerticalGroup(
            panNombreEnpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panNombreEnpresaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAutorizacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAgregarProducto.setText("AGREGAR PRODUCTO");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });

        btnImprimirFactura.setText("IMPRIMIR FACTURA");
        btnImprimirFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirFacturaActionPerformed(evt);
            }
        });

        btnAgregarCliente.setText("AGREGAR DATOS CLIENTE");
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });

        btnCancelarPedido.setText("CANCELAR PEDIDO");
        btnCancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPedidoActionPerformed(evt);
            }
        });

        lblImagenLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N

        javax.swing.GroupLayout panNombreEmpresaLayout = new javax.swing.GroupLayout(panNombreEmpresa);
        panNombreEmpresa.setLayout(panNombreEmpresaLayout);
        panNombreEmpresaLayout.setHorizontalGroup(
            panNombreEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panNombreEmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panNombreEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panNombreEmpresaLayout.createSequentialGroup()
                        .addGroup(panNombreEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panProductosCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panNombreEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panMetodoPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(panDatosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panNombreEmpresaLayout.createSequentialGroup()
                        .addComponent(btnAgregarProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelarPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImprimirFactura))
                    .addGroup(panNombreEmpresaLayout.createSequentialGroup()
                        .addComponent(lblImagenLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panNombreEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panNombreEnpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panNombreEmpresaLayout.setVerticalGroup(
            panNombreEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panNombreEmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panNombreEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panNombreEmpresaLayout.createSequentialGroup()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panNombreEnpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblImagenLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panDatosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panNombreEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panNombreEmpresaLayout.createSequentialGroup()
                        .addComponent(panMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panNombreEmpresaLayout.createSequentialGroup()
                        .addComponent(btnAgregarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panProductosCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panNombreEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimirFactura)
                    .addComponent(btnAgregarProducto)
                    .addComponent(btnCancelarPedido))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panNombreEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnImprimirFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirFacturaActionPerformed
        Nombre =txtNombre.getText();
        Apellido =txtApellido.getText();
        Telefono =txtNumeroCelular.getText();
        ImprimirFactura imprimir = new ImprimirFactura(new javax.swing.JFrame(), true);
        imprimir.setVisible(true);
        /*if(rbtnTarjetaCredito.isSelected()){
            TarjetaCredito=rbtnTarjetaCredito.getText();   
        }
        else if (rbtnTarjetaDebito.isSelected()){
            TarjetaDebito=rbtnTarjetaDebito.getText();
        }
        else if (rbtnEfecivo.isSelected()){
            Efectivo = rbtnEfecivo.getText();
        }
        if (rbtnDebidoBancario.isSelected()){
            DebitoBancario=rbtnDebidoBancario.getText();
        }*/
    }//GEN-LAST:event_btnImprimirFacturaActionPerformed
    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        DatosCliente datosCliente = new DatosCliente(new javax.swing.JFrame(), true);
        datosCliente.setVisible(true);
    }//GEN-LAST:event_btnAgregarClienteActionPerformed
    private void btnCancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPedidoActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarPedidoActionPerformed
    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Compra dialog = new Compra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnCancelarPedido;
    private javax.swing.JButton btnImprimirFactura;
    public static javax.swing.ButtonGroup btngMetodoPago;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    public static javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblAutorizacion;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblImagenLogo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumeroCelular;
    private javax.swing.JLabel lblPrecioConIVA;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalSinIVA;
    private javax.swing.JLabel lblValorIVA;
    private javax.swing.JPanel panDatosCliente;
    private javax.swing.JPanel panFactura;
    private javax.swing.JPanel panMetodoPago;
    private javax.swing.JPanel panNombreEmpresa;
    private javax.swing.JPanel panNombreEnpresa;
    private javax.swing.JPanel panProductosCompra;
    public static javax.swing.JRadioButton rbtnDebidoBancario;
    public static javax.swing.JRadioButton rbtnEfecivo;
    public static javax.swing.JRadioButton rbtnTarjetaCredito;
    public static javax.swing.JRadioButton rbtnTarjetaDebito;
    public static javax.swing.JTable tblProductos;
    public static javax.swing.JTextField txtApellido;
    public static javax.swing.JTextField txtCedula;
    public static javax.swing.JTextField txtNombre;
    public static javax.swing.JTextField txtNumeroCelular;
    public static javax.swing.JTextField txtPrecioConIVA;
    public static javax.swing.JTextField txtSubtotal;
    public static javax.swing.JTextField txtTotal;
    public static javax.swing.JTextField txtTotalSinIVA;
    public static javax.swing.JTextField txtValorDelIVA;
    // End of variables declaration//GEN-END:variables
}
