/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Victor Nivelo
 */
public class MateriaPrima extends javax.swing.JDialog {

    /**
     * Creates new form MateriaPrima
     */
    
    DefaultTableModel modelo;
    public MateriaPrima(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        modelo = new DefaultTableModel();
        modelo.addColumn("PRODUCTO");
        modelo.addColumn("CANTIDAD");
        modelo.addColumn("TOTAL");
        this.tblCompra.setModel(modelo);  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panMateriaPrima = new javax.swing.JPanel();
        lblMateriaPrima = new javax.swing.JLabel();
        panProductos = new javax.swing.JPanel();
        lblImagenConos = new javax.swing.JLabel();
        lblImagenPaletas = new javax.swing.JLabel();
        lblImagenPlasticos = new javax.swing.JLabel();
        lblImagenGalletas = new javax.swing.JLabel();
        sprPaletas = new javax.swing.JSpinner();
        sprConos = new javax.swing.JSpinner();
        sprPlatos = new javax.swing.JSpinner();
        sprGalletas = new javax.swing.JSpinner();
        btnRealizarPedido = new javax.swing.JButton();
        btnCancelarPedido = new javax.swing.JButton();
        lblPrecioPaletas = new javax.swing.JLabel();
        lblPrecioCono = new javax.swing.JLabel();
        lblPrecioPlatos = new javax.swing.JLabel();
        lblPrecioGalleta = new javax.swing.JLabel();
        lblNombrePaletas = new javax.swing.JLabel();
        lblNombreConos = new javax.swing.JLabel();
        lblNombrePlatos = new javax.swing.JLabel();
        lblNombreGalletas = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnCalcularTotal = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompra = new javax.swing.JTable();
        btnAgregarPaletas = new javax.swing.JButton();
        btnAgregarConos = new javax.swing.JButton();
        btnAgregarPlatos = new javax.swing.JButton();
        btnAgregarGalletas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PEDIDO DE MATERIA PRIMA");

        panMateriaPrima.setBackground(new java.awt.Color(255, 204, 204));

        lblMateriaPrima.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblMateriaPrima.setForeground(new java.awt.Color(255, 51, 51));
        lblMateriaPrima.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMateriaPrima.setText("Pedido de materia prima para helados");

        panProductos.setBackground(new java.awt.Color(255, 204, 204));
        panProductos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "PRODUCTOS"));

        lblImagenConos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/conos-removebg-preview.png"))); // NOI18N

        lblImagenPaletas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Paletas-removebg-preview.png"))); // NOI18N

        lblImagenPlasticos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Platos_plasticos-removebg-preview.png"))); // NOI18N

        lblImagenGalletas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Galletas-removebg-preview.png"))); // NOI18N

        sprPaletas.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        sprConos.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        sprPlatos.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        sprGalletas.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        btnRealizarPedido.setText("REALIZAR PEDIDO");
        btnRealizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarPedidoActionPerformed(evt);
            }
        });

        btnCancelarPedido.setText("CANCELAR PEDIDO");
        btnCancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPedidoActionPerformed(evt);
            }
        });

        lblPrecioPaletas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrecioPaletas.setText("PRECIO: $ 1");

        lblPrecioCono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrecioCono.setText("PRECIO: $ 1.25");

        lblPrecioPlatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrecioPlatos.setText("PRECIO: $ 1.75");

        lblPrecioGalleta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrecioGalleta.setText("PRECIO: $ 1.50");

        lblNombrePaletas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombrePaletas.setText("PALETAS");

        lblNombreConos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreConos.setText("CONOS");

        lblNombrePlatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombrePlatos.setText("PLATOS PLASTICOS");

        lblNombreGalletas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreGalletas.setText("GALLETAS");

        lblTotal.setText("VALOR TOTAL");

        btnCalcularTotal.setText("CALCULAR TOTAL");
        btnCalcularTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularTotalActionPerformed(evt);
            }
        });

        tblCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Paletas", "30", "30.00"},
                {"Conos", "35", "43.75"},
                {"Platos", "20", "35.00"},
                {"Galletas", "13", "19.50"}
            },
            new String [] {
                "Producto", "Cantidad", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblCompra);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnAgregarPaletas.setText("AGREGAR PALETA");
        btnAgregarPaletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPaletasActionPerformed(evt);
            }
        });

        btnAgregarConos.setText("AGREGAR CONO");
        btnAgregarConos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarConosActionPerformed(evt);
            }
        });

        btnAgregarPlatos.setText("AGREGAR PLATO");
        btnAgregarPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPlatosActionPerformed(evt);
            }
        });

        btnAgregarGalletas.setText("AGREGAR GALLETA");
        btnAgregarGalletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarGalletasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panProductosLayout = new javax.swing.GroupLayout(panProductos);
        panProductos.setLayout(panProductosLayout);
        panProductosLayout.setHorizontalGroup(
            panProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panProductosLayout.createSequentialGroup()
                .addGroup(panProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panProductosLayout.createSequentialGroup()
                        .addComponent(lblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalcularTotal))
                    .addGroup(panProductosLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelarPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRealizarPedido))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panProductosLayout.createSequentialGroup()
                        .addGroup(panProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panProductosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnAgregarPaletas, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAgregarConos, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panProductosLayout.createSequentialGroup()
                                .addGroup(panProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombrePaletas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblImagenPaletas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addGroup(panProductosLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(panProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPrecioPaletas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(sprPaletas))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblImagenConos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblNombreConos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lblPrecioCono, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sprConos, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(panProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblImagenPlasticos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sprPlatos)
                            .addComponent(lblPrecioPlatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNombrePlatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgregarPlatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblImagenGalletas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sprGalletas)
                            .addComponent(lblPrecioGalleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNombreGalletas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgregarGalletas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panProductosLayout.setVerticalGroup(
            panProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblImagenPaletas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblImagenPlasticos)
                        .addComponent(lblImagenGalletas))
                    .addComponent(lblImagenConos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombrePaletas)
                    .addComponent(lblNombreConos)
                    .addComponent(lblNombrePlatos)
                    .addComponent(lblNombreGalletas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sprPaletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sprConos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sprPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sprGalletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioPaletas)
                    .addComponent(lblPrecioCono)
                    .addComponent(lblPrecioPlatos)
                    .addComponent(lblPrecioGalleta))
                .addGap(7, 7, 7)
                .addGroup(panProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarPaletas)
                    .addComponent(btnAgregarConos)
                    .addComponent(btnAgregarPlatos)
                    .addComponent(btnAgregarGalletas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcularTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRealizarPedido)
                    .addComponent(btnCancelarPedido)))
        );

        javax.swing.GroupLayout panMateriaPrimaLayout = new javax.swing.GroupLayout(panMateriaPrima);
        panMateriaPrima.setLayout(panMateriaPrimaLayout);
        panMateriaPrimaLayout.setHorizontalGroup(
            panMateriaPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMateriaPrimaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panMateriaPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMateriaPrima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panMateriaPrimaLayout.createSequentialGroup()
                        .addComponent(panProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panMateriaPrimaLayout.setVerticalGroup(
            panMateriaPrimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMateriaPrimaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMateriaPrima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnCancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPedidoActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarPedidoActionPerformed
    private void btnAgregarPaletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPaletasActionPerformed
        String []agregar = new String[3];
        agregar[0]=lblNombrePaletas.getText();
        agregar[1]=sprPaletas.getValue().toString();
        agregar[2]=("$ 30.00");
        modelo.addRow(agregar);
    }//GEN-LAST:event_btnAgregarPaletasActionPerformed
    private void btnAgregarConosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarConosActionPerformed
        String []agregar = new String[3];
        agregar[0]=lblNombreConos.getText();
        agregar[1]=sprConos.getValue().toString();
        agregar[2]=("$ 62.50");
        modelo.addRow(agregar);
    }//GEN-LAST:event_btnAgregarConosActionPerformed
    private void btnAgregarPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPlatosActionPerformed
        String []agregar = new String[3];
        agregar[0]=lblNombrePlatos.getText();
        agregar[1]=sprPlatos.getValue().toString();
        agregar[2]=("$ 26.25");
        modelo.addRow(agregar);
    }//GEN-LAST:event_btnAgregarPlatosActionPerformed
    private void btnAgregarGalletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarGalletasActionPerformed
        String []agregar = new String[3];
        agregar[0]=lblNombreGalletas.getText();
        agregar[1]=sprGalletas.getValue().toString();
        agregar[2]=("$ 52.50");
        modelo.addRow(agregar);
    }//GEN-LAST:event_btnAgregarGalletasActionPerformed

    private void btnRealizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarPedidoActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnRealizarPedidoActionPerformed

    private void btnCalcularTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularTotalActionPerformed
        
        txtTotal.setText("128.25");
    }//GEN-LAST:event_btnCalcularTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MateriaPrima dialog = new MateriaPrima(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarConos;
    private javax.swing.JButton btnAgregarGalletas;
    private javax.swing.JButton btnAgregarPaletas;
    private javax.swing.JButton btnAgregarPlatos;
    private javax.swing.JButton btnCalcularTotal;
    private javax.swing.JButton btnCancelarPedido;
    private javax.swing.JButton btnRealizarPedido;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImagenConos;
    private javax.swing.JLabel lblImagenGalletas;
    private javax.swing.JLabel lblImagenPaletas;
    private javax.swing.JLabel lblImagenPlasticos;
    private javax.swing.JLabel lblMateriaPrima;
    private javax.swing.JLabel lblNombreConos;
    private javax.swing.JLabel lblNombreGalletas;
    private javax.swing.JLabel lblNombrePaletas;
    private javax.swing.JLabel lblNombrePlatos;
    private javax.swing.JLabel lblPrecioCono;
    private javax.swing.JLabel lblPrecioGalleta;
    private javax.swing.JLabel lblPrecioPaletas;
    private javax.swing.JLabel lblPrecioPlatos;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panMateriaPrima;
    private javax.swing.JPanel panProductos;
    private javax.swing.JSpinner sprConos;
    private javax.swing.JSpinner sprGalletas;
    private javax.swing.JSpinner sprPaletas;
    private javax.swing.JSpinner sprPlatos;
    private javax.swing.JTable tblCompra;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
