/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.table.DefaultTableModel;
/**
 * @author Victor Nivelo
 */
public class PantallaHeladeria extends javax.swing.JFrame {

    /**
     * Creates new form PantallaHeladeria
     */
    DefaultTableModel modelo;
        
    public PantallaHeladeria() {
        initComponents();
        this.setLocationRelativeTo(null);
        modelo = new DefaultTableModel();
        modelo.addColumn("Producto");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio");
        this.tblListaCompra.setModel(modelo);
        }  
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panHeladeria = new javax.swing.JPanel();
        lblBienvenida = new javax.swing.JLabel();
        panProductos = new javax.swing.JPanel();
        panHelados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listHelado = new javax.swing.JList<>();
        lblHelado = new javax.swing.JLabel();
        sprHelado = new javax.swing.JSpinner();
        lblImagenhelado = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panConos = new javax.swing.JPanel();
        lblCono = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listCono = new javax.swing.JList<>();
        sprCono = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panGalleta = new javax.swing.JPanel();
        lblGalleta = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listGalleta = new javax.swing.JList<>();
        sprGalleta = new javax.swing.JSpinner();
        panPastel = new javax.swing.JPanel();
        lblPastel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listPastel = new javax.swing.JList<>();
        sprPastel = new javax.swing.JSpinner();
        btnRealizarCompra = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnIngresarRegistro = new javax.swing.JButton();
        panListaDeCompra = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListaCompra = new javax.swing.JTable();
        btnAgregarHelado = new javax.swing.JButton();
        btnAgregarCono = new javax.swing.JButton();
        btnAgregarGalleta = new javax.swing.JButton();
        btnAgregarPastel = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        lblFormatoTitulo = new javax.swing.JLabel();
        lblNombreHeladeria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HELADERIA PINGUINO");
        setForeground(new java.awt.Color(204, 255, 255));

        panHeladeria.setBackground(new java.awt.Color(204, 255, 255));
        panHeladeria.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 1, true));

        lblBienvenida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenida.setText("Bienvenido a la heladeria pinguino le podemos ofrecer los siguientes productos:");

        panProductos.setBackground(new java.awt.Color(204, 255, 255));
        panProductos.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true), "HELADOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 0, 0))); // NOI18N

        panHelados.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 153), 1, true));

        listHelado.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Chocolate", "Menta", "Vainilla", "Mango", "Fresa", "Cereza" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listHelado);

        lblHelado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblHelado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHelado.setText("Helado");

        sprHelado.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout panHeladosLayout = new javax.swing.GroupLayout(panHelados);
        panHelados.setLayout(panHeladosLayout);
        panHeladosLayout.setHorizontalGroup(
            panHeladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHeladosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panHeladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sprHelado)
                    .addComponent(lblHelado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addContainerGap())
        );
        panHeladosLayout.setVerticalGroup(
            panHeladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panHeladosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHelado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sprHelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblImagenhelado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagenhelado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Paleta-removebg-preview.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cono-removebg-preview.png"))); // NOI18N

        panConos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 1, true));

        lblCono.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblCono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCono.setText("Cono");

        listCono.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Cono de chocolate", "Cono de vainilla", "Cono de fresa", "Cono de cereza" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listCono);

        sprCono.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout panConosLayout = new javax.swing.GroupLayout(panConos);
        panConos.setLayout(panConosLayout);
        panConosLayout.setHorizontalGroup(
            panConosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panConosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sprCono)
                    .addComponent(lblCono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addContainerGap())
        );
        panConosLayout.setVerticalGroup(
            panConosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panConosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sprCono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pastel_helado-removebg-preview.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Galleta_helada-removebg-preview.png"))); // NOI18N

        panGalleta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 1, true));

        lblGalleta.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblGalleta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGalleta.setText("Galleta Helada");

        listGalleta.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Galletas de menta", "Galleta de chocolate", "Galleta de fresa", "Galleta de vainilla", "Galleta de limon" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(listGalleta);

        sprGalleta.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout panGalletaLayout = new javax.swing.GroupLayout(panGalleta);
        panGalleta.setLayout(panGalletaLayout);
        panGalletaLayout.setHorizontalGroup(
            panGalletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panGalletaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panGalletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(lblGalleta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sprGalleta, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        panGalletaLayout.setVerticalGroup(
            panGalletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panGalletaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGalleta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sprGalleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panPastel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 1, true));

        lblPastel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblPastel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPastel.setText("Pastel helado");

        listPastel.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Pastel helado de gelatina", "Pastel helado de 3 capas", "Pastel helado de durazno" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(listPastel);

        sprPastel.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout panPastelLayout = new javax.swing.GroupLayout(panPastel);
        panPastel.setLayout(panPastelLayout);
        panPastelLayout.setHorizontalGroup(
            panPastelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panPastelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panPastelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sprPastel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPastel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
        );
        panPastelLayout.setVerticalGroup(
            panPastelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPastelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPastel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sprPastel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnRealizarCompra.setText("REALIZAR COMPRA");
        btnRealizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarCompraActionPerformed(evt);
            }
        });

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnIngresarRegistro.setText("INGRESAR A REGISTRO");
        btnIngresarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarRegistroActionPerformed(evt);
            }
        });

        panListaDeCompra.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true), "LISTA DE COMPRA"));

        tblListaCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "", "", ""
            }
        ));
        jScrollPane2.setViewportView(tblListaCompra);

        javax.swing.GroupLayout panListaDeCompraLayout = new javax.swing.GroupLayout(panListaDeCompra);
        panListaDeCompra.setLayout(panListaDeCompraLayout);
        panListaDeCompraLayout.setHorizontalGroup(
            panListaDeCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panListaDeCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
                .addContainerGap())
        );
        panListaDeCompraLayout.setVerticalGroup(
            panListaDeCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panListaDeCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAgregarHelado.setText("AGREGAR HELADO");
        btnAgregarHelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarHeladoActionPerformed(evt);
            }
        });

        btnAgregarCono.setText("AGREGAR CONO");
        btnAgregarCono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarConoActionPerformed(evt);
            }
        });

        btnAgregarGalleta.setText("AGREGAR GALLETA");
        btnAgregarGalleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarGalletaActionPerformed(evt);
            }
        });

        btnAgregarPastel.setText("AGREGAR PASTEL");
        btnAgregarPastel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPastelActionPerformed(evt);
            }
        });

        btnEliminarProducto.setText("ELIMINAR PRODUCTO");
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panProductosLayout = new javax.swing.GroupLayout(panProductos);
        panProductos.setLayout(panProductosLayout);
        panProductosLayout.setHorizontalGroup(
            panProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panProductosLayout.createSequentialGroup()
                .addComponent(btnIngresarRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRealizarCompra))
            .addGroup(panProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panProductosLayout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(lblImagenhelado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panProductosLayout.createSequentialGroup()
                        .addComponent(panHelados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panProductosLayout.createSequentialGroup()
                        .addComponent(btnAgregarHelado, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panProductosLayout.createSequentialGroup()
                        .addComponent(btnAgregarCono, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregarGalleta, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregarPastel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panProductosLayout.createSequentialGroup()
                        .addComponent(panConos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panGalleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panPastel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panProductosLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panProductosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panListaDeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panProductosLayout.setVerticalGroup(
            panProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblImagenhelado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panHelados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panConos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panGalleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panPastel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarHelado)
                    .addComponent(btnAgregarCono)
                    .addComponent(btnAgregarGalleta)
                    .addComponent(btnAgregarPastel))
                .addGap(3, 3, 3)
                .addComponent(panListaDeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIngresarRegistro, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRealizarCompra)
                        .addComponent(btnSalir)
                        .addComponent(btnEliminarProducto)))
                .addContainerGap())
        );

        lblFormatoTitulo.setBackground(new java.awt.Color(153, 255, 204));
        lblFormatoTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Titulo_Heladeria.png"))); // NOI18N

        lblNombreHeladeria.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblNombreHeladeria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreHeladeria.setText("Heladeria Pinguino");

        javax.swing.GroupLayout panHeladeriaLayout = new javax.swing.GroupLayout(panHeladeria);
        panHeladeria.setLayout(panHeladeriaLayout);
        panHeladeriaLayout.setHorizontalGroup(
            panHeladeriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHeladeriaLayout.createSequentialGroup()
                .addComponent(lblFormatoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(panHeladeriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panHeladeriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panHeladeriaLayout.createSequentialGroup()
                        .addGroup(panHeladeriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNombreHeladeria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panHeladeriaLayout.setVerticalGroup(
            panHeladeriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHeladeriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFormatoTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreHeladeria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panHeladeria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panHeladeria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnIngresarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarRegistroActionPerformed
        AccesoARegistro accesoARegistro = new AccesoARegistro(this, true);
        accesoARegistro.setVisible(true);
    }//GEN-LAST:event_btnIngresarRegistroActionPerformed
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed
    private void btnRealizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarCompraActionPerformed
        Compra compra = new Compra(this, true);
        compra.setVisible(true);
    }//GEN-LAST:event_btnRealizarCompraActionPerformed
    private void btnAgregarHeladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarHeladoActionPerformed
        String []agregar = new String[3];
        agregar[0]=listHelado.getSelectedValue();
        agregar[1]=sprHelado.getValue().toString();
        agregar[2]=("$ 0.75");
        modelo.addRow(agregar);
    }//GEN-LAST:event_btnAgregarHeladoActionPerformed
    private void btnAgregarConoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarConoActionPerformed
        String []agregar = new String[3];
        agregar[0]=listCono.getSelectedValue();
        agregar[1]=sprCono.getValue().toString();
        agregar[2]=("$ 1.50");
        modelo.addRow(agregar);
    }//GEN-LAST:event_btnAgregarConoActionPerformed
    private void btnAgregarGalletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarGalletaActionPerformed
        String []agregar = new String[3];
        agregar[0]=listGalleta.getSelectedValue();
        agregar[1]=sprGalleta.getValue().toString();
        agregar[2]=("$ 1.00");
        modelo.addRow(agregar);
    }//GEN-LAST:event_btnAgregarGalletaActionPerformed
    private void btnAgregarPastelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPastelActionPerformed
        String []agregar = new String[3];
        agregar[0]=listPastel.getSelectedValue();
        agregar[1]=sprPastel.getValue().toString();
        agregar[2]=("$ 2.50");
        modelo.addRow(agregar);
    }//GEN-LAST:event_btnAgregarPastelActionPerformed
    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        int fila = tblListaCompra.getSelectedRow();
        modelo.removeRow(fila);
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaHeladeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaHeladeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaHeladeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaHeladeria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaHeladeria().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCono;
    private javax.swing.JButton btnAgregarGalleta;
    private javax.swing.JButton btnAgregarHelado;
    private javax.swing.JButton btnAgregarPastel;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnIngresarRegistro;
    private javax.swing.JButton btnRealizarCompra;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblCono;
    private javax.swing.JLabel lblFormatoTitulo;
    private javax.swing.JLabel lblGalleta;
    private javax.swing.JLabel lblHelado;
    private javax.swing.JLabel lblImagenhelado;
    private javax.swing.JLabel lblNombreHeladeria;
    private javax.swing.JLabel lblPastel;
    private javax.swing.JList<String> listCono;
    private javax.swing.JList<String> listGalleta;
    public static javax.swing.JList<String> listHelado;
    private javax.swing.JList<String> listPastel;
    private javax.swing.JPanel panConos;
    private javax.swing.JPanel panGalleta;
    private javax.swing.JPanel panHeladeria;
    private javax.swing.JPanel panHelados;
    private javax.swing.JPanel panListaDeCompra;
    public static javax.swing.JPanel panPastel;
    private javax.swing.JPanel panProductos;
    public static javax.swing.JSpinner sprCono;
    public static javax.swing.JSpinner sprGalleta;
    public static javax.swing.JSpinner sprHelado;
    private javax.swing.JSpinner sprPastel;
    public static javax.swing.JTable tblListaCompra;
    // End of variables declaration//GEN-END:variables
}