/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Victor Nivelo
 */
public class Registro extends javax.swing.JDialog {

    /**
     * Creates new form RegistroVentas
     */
    DefaultTableModel modelo;
    DefaultTableModel modeloc;
    
    public Registro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        modeloc = new DefaultTableModel();
        modeloc.addColumn("Cliente");
        modeloc.addColumn("Medoto de pago");
        modeloc.addColumn("Producto");
        modeloc.addColumn("Cantidad");
        modeloc.addColumn("Precio");
        modeloc.addColumn("Total");
        this.tblRegistroVentas.setModel(modeloc);
        
        modelo = new DefaultTableModel();
        modelo.addColumn("Producto");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio");
        modelo.addColumn("Total");
        this.tblCompras.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        panVentas = new javax.swing.JPanel();
        lblRegistroVentas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRegistroVentas = new javax.swing.JTable();
        btnCalcularGanancias = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnSalirRegistro = new javax.swing.JButton();
        panCompras = new javax.swing.JPanel();
        lblRegistroCompras = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompras = new javax.swing.JTable();
        btnCalcularCostos = new javax.swing.JButton();
        lblTotalCompras = new javax.swing.JLabel();
        txtTotalCompras = new javax.swing.JTextField();
        btnComprarMateriaPrima = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REGISTRO GERENTE");

        jSplitPane1.setBackground(new java.awt.Color(204, 255, 204));
        jSplitPane1.setDividerLocation(500);

        panVentas.setBackground(new java.awt.Color(204, 255, 204));
        panVentas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 51), 1, true));

        lblRegistroVentas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblRegistroVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistroVentas.setText("Registro de ventas");

        tblRegistroVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Victor David", "Tarjeta de credito", "6.94"},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cliente", "Metodo de pago", "Total"
            }
        ));
        jScrollPane2.setViewportView(tblRegistroVentas);

        btnCalcularGanancias.setText("CALCULAR GANANCIAS");
        btnCalcularGanancias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularGananciasActionPerformed(evt);
            }
        });

        lblTotal.setText("TOTAL");

        btnSalirRegistro.setText("SALIR DEL REGISTRO");
        btnSalirRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panVentasLayout = new javax.swing.GroupLayout(panVentas);
        panVentas.setLayout(panVentasLayout);
        panVentasLayout.setHorizontalGroup(
            panVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addComponent(lblRegistroVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panVentasLayout.createSequentialGroup()
                        .addComponent(lblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalcularGanancias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalirRegistro)))
                .addContainerGap())
        );
        panVentasLayout.setVerticalGroup(
            panVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegistroVentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcularGanancias)
                    .addComponent(lblTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalirRegistro))
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(panVentas);

        panCompras.setBackground(new java.awt.Color(255, 204, 204));
        panCompras.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));

        lblRegistroCompras.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblRegistroCompras.setText("Registro de compras de materia prima");

        tblCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblCompras);

        btnCalcularCostos.setText("CALCULAR COSTOS");
        btnCalcularCostos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularCostosActionPerformed(evt);
            }
        });

        lblTotalCompras.setText("TOTAL");

        btnComprarMateriaPrima.setText("COMPRAR");
        btnComprarMateriaPrima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarMateriaPrimaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panComprasLayout = new javax.swing.GroupLayout(panCompras);
        panCompras.setLayout(panComprasLayout);
        panComprasLayout.setHorizontalGroup(
            panComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panComprasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRegistroCompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panComprasLayout.createSequentialGroup()
                        .addComponent(lblTotalCompras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalcularCostos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnComprarMateriaPrima))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        panComprasLayout.setVerticalGroup(
            panComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panComprasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegistroCompras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcularCostos)
                    .addComponent(lblTotalCompras)
                    .addComponent(txtTotalCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComprarMateriaPrima))
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(panCompras);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnComprarMateriaPrimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarMateriaPrimaActionPerformed
        MateriaPrima materiaPrima = new MateriaPrima(new javax.swing.JFrame(), true);
        materiaPrima.setVisible(true);
    }//GEN-LAST:event_btnComprarMateriaPrimaActionPerformed

    private void btnCalcularCostosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularCostosActionPerformed
        String []agregar = new String[4];
        agregar[0]=("Palelas");
        agregar[1]=("1");
        agregar[2]=("30");
        agregar [3]=("$30");
        modelo.addRow(agregar);
        agregar[0]=("Conos");
        agregar[1]=("1.25");
        agregar[2]=("50");
        agregar [3]=("62.50");
        modelo.addRow(agregar);
        agregar[0]=("Platos");
        agregar[1]=("1.75");
        agregar[2]=("15");
        agregar [3]=("26.25");
        modelo.addRow(agregar);
        agregar[0]=("Galletas");
        agregar[1]=("1.50");
        agregar[2]=("35");
        agregar [3]=("52.50");
        modelo.addRow(agregar);
        txtTotalCompras.setText("128.25");
    }//GEN-LAST:event_btnCalcularCostosActionPerformed

    private void btnSalirRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirRegistroActionPerformed
        this.dispose();
        /*AccesoARegistro accesoARegistro = new AccesoARegistro(new javax.swing.JFrame(), true);
        accesoARegistro.setVisible(true);*/
    }//GEN-LAST:event_btnSalirRegistroActionPerformed

    private void btnCalcularGananciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularGananciasActionPerformed
        String []agregar = new String[6];
        agregar[0]=("Victor David");
        agregar[1]=("Tarjeta de credito");
        agregar [2]=("Helados");
        agregar [3]=("7");
        agregar [4]=("5.75");
        agregar [5]=("6.94");
        modeloc.addRow(agregar);
        txtTotal.setText("6.94");
    }//GEN-LAST:event_btnCalcularGananciasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Registro dialog = new Registro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularCostos;
    private javax.swing.JButton btnCalcularGanancias;
    private javax.swing.JButton btnComprarMateriaPrima;
    private javax.swing.JButton btnSalirRegistro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblRegistroCompras;
    private javax.swing.JLabel lblRegistroVentas;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalCompras;
    private javax.swing.JPanel panCompras;
    private javax.swing.JPanel panVentas;
    private javax.swing.JTable tblCompras;
    private javax.swing.JTable tblRegistroVentas;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalCompras;
    // End of variables declaration//GEN-END:variables
}
